// Code generated by protoc-gen-go.
// source: network.proto
// DO NOT EDIT!

package network

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ServerHello struct {
	CodeName          *string `protobuf:"bytes,1,opt,name=code_name" json:"code_name,omitempty"`
	VersionNumber     *string `protobuf:"bytes,2,opt,name=version_number" json:"version_number,omitempty"`
	MinHashHeight     *int32  `protobuf:"varint,8,opt,name=min_hash_height,def=8" json:"min_hash_height,omitempty"`
	MaxHashListLength *int32  `protobuf:"varint,9,opt,name=max_hash_list_length,def=32" json:"max_hash_list_length,omitempty"`
	MaxDataBlockSize  *int32  `protobuf:"varint,10,opt,name=max_data_block_size,def=1024" json:"max_data_block_size,omitempty"`
	ServerNick        *string `protobuf:"bytes,99,opt,name=server_nick" json:"server_nick,omitempty"`
	ServerMsg         *string `protobuf:"bytes,100,opt,name=server_msg" json:"server_msg,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *ServerHello) Reset()         { *m = ServerHello{} }
func (m *ServerHello) String() string { return proto.CompactTextString(m) }
func (*ServerHello) ProtoMessage()    {}

const Default_ServerHello_MinHashHeight int32 = 8
const Default_ServerHello_MaxHashListLength int32 = 32
const Default_ServerHello_MaxDataBlockSize int32 = 1024

func (m *ServerHello) GetCodeName() string {
	if m != nil && m.CodeName != nil {
		return *m.CodeName
	}
	return ""
}

func (m *ServerHello) GetVersionNumber() string {
	if m != nil && m.VersionNumber != nil {
		return *m.VersionNumber
	}
	return ""
}

func (m *ServerHello) GetMinHashHeight() int32 {
	if m != nil && m.MinHashHeight != nil {
		return *m.MinHashHeight
	}
	return Default_ServerHello_MinHashHeight
}

func (m *ServerHello) GetMaxHashListLength() int32 {
	if m != nil && m.MaxHashListLength != nil {
		return *m.MaxHashListLength
	}
	return Default_ServerHello_MaxHashListLength
}

func (m *ServerHello) GetMaxDataBlockSize() int32 {
	if m != nil && m.MaxDataBlockSize != nil {
		return *m.MaxDataBlockSize
	}
	return Default_ServerHello_MaxDataBlockSize
}

func (m *ServerHello) GetServerNick() string {
	if m != nil && m.ServerNick != nil {
		return *m.ServerNick
	}
	return ""
}

func (m *ServerHello) GetServerMsg() string {
	if m != nil && m.ServerMsg != nil {
		return *m.ServerMsg
	}
	return ""
}

type StaticId struct {
	Length           *int64 `protobuf:"varint,1,req,name=length" json:"length,omitempty"`
	Hash             []byte `protobuf:"bytes,2,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StaticId) Reset()         { *m = StaticId{} }
func (m *StaticId) String() string { return proto.CompactTextString(m) }
func (*StaticId) ProtoMessage()    {}

func (m *StaticId) GetLength() int64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *StaticId) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type InnerHashes struct {
	Height           *int32 `protobuf:"varint,1,req,name=height" json:"height,omitempty"`
	From             *int32 `protobuf:"varint,2,req,name=from" json:"from,omitempty"`
	Length           *int32 `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	Hashes           []byte `protobuf:"bytes,8,opt,name=hashes" json:"hashes,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *InnerHashes) Reset()         { *m = InnerHashes{} }
func (m *InnerHashes) String() string { return proto.CompactTextString(m) }
func (*InnerHashes) ProtoMessage()    {}

func (m *InnerHashes) GetHeight() int32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *InnerHashes) GetFrom() int32 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *InnerHashes) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *InnerHashes) GetHashes() []byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type FileData struct {
	From             *int64 `protobuf:"varint,2,req,name=from" json:"from,omitempty"`
	Length           *int32 `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	InBlocks         *int32 `protobuf:"varint,4,opt,name=in_blocks,def=1024" json:"in_blocks,omitempty"`
	Data             []byte `protobuf:"bytes,8,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FileData) Reset()         { *m = FileData{} }
func (m *FileData) String() string { return proto.CompactTextString(m) }
func (*FileData) ProtoMessage()    {}

const Default_FileData_InBlocks int32 = 1024

func (m *FileData) GetFrom() int64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *FileData) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *FileData) GetInBlocks() int32 {
	if m != nil && m.InBlocks != nil {
		return *m.InBlocks
	}
	return Default_FileData_InBlocks
}

func (m *FileData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type HaveFile struct {
	HaveRequest      *bool  `protobuf:"varint,1,opt,name=have_request" json:"have_request,omitempty"`
	Complete         *bool  `protobuf:"varint,2,opt,name=complete" json:"complete,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HaveFile) Reset()         { *m = HaveFile{} }
func (m *HaveFile) String() string { return proto.CompactTextString(m) }
func (*HaveFile) ProtoMessage()    {}

func (m *HaveFile) GetHaveRequest() bool {
	if m != nil && m.HaveRequest != nil {
		return *m.HaveRequest
	}
	return false
}

func (m *HaveFile) GetComplete() bool {
	if m != nil && m.Complete != nil {
		return *m.Complete
	}
	return false
}

type File struct {
	Id               *StaticId      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Have             *HaveFile      `protobuf:"bytes,2,opt,name=have" json:"have,omitempty"`
	HashAsk          []*InnerHashes `protobuf:"bytes,4,rep,name=hash_ask" json:"hash_ask,omitempty"`
	HashSend         []*InnerHashes `protobuf:"bytes,5,rep,name=hash_send" json:"hash_send,omitempty"`
	DataAsk          []*FileData    `protobuf:"bytes,6,rep,name=data_ask" json:"data_ask,omitempty"`
	DataSend         []*FileData    `protobuf:"bytes,7,rep,name=data_send" json:"data_send,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}

func (m *File) GetId() *StaticId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *File) GetHave() *HaveFile {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *File) GetHashAsk() []*InnerHashes {
	if m != nil {
		return m.HashAsk
	}
	return nil
}

func (m *File) GetHashSend() []*InnerHashes {
	if m != nil {
		return m.HashSend
	}
	return nil
}

func (m *File) GetDataAsk() []*FileData {
	if m != nil {
		return m.DataAsk
	}
	return nil
}

func (m *File) GetDataSend() []*FileData {
	if m != nil {
		return m.DataSend
	}
	return nil
}

type Retains struct {
	Add              []*StaticLink `protobuf:"bytes,1,rep,name=add" json:"add,omitempty"`
	Remove           []*StaticId   `protobuf:"bytes,2,rep,name=remove" json:"remove,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Retains) Reset()         { *m = Retains{} }
func (m *Retains) String() string { return proto.CompactTextString(m) }
func (*Retains) ProtoMessage()    {}

func (m *Retains) GetAdd() []*StaticLink {
	if m != nil {
		return m.Add
	}
	return nil
}

func (m *Retains) GetRemove() []*StaticId {
	if m != nil {
		return m.Remove
	}
	return nil
}

type Packet struct {
	Hello            *ServerHello `protobuf:"bytes,2,opt,name=hello" json:"hello,omitempty"`
	HelloRequest     *bool        `protobuf:"varint,3,opt,name=hello_request" json:"hello_request,omitempty"`
	Retains          []*Retains   `protobuf:"bytes,4,rep,name=retains" json:"retains,omitempty"`
	Files            []*File      `protobuf:"bytes,5,rep,name=files" json:"files,omitempty"`
	RequestId        []byte       `protobuf:"bytes,6,opt,name=request_id" json:"request_id,omitempty"`
	ReplyIds         [][]byte     `protobuf:"bytes,7,rep,name=reply_ids" json:"reply_ids,omitempty"`
	Bebug            []string     `protobuf:"bytes,900,rep,name=bebug" json:"bebug,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}

func (m *Packet) GetHello() *ServerHello {
	if m != nil {
		return m.Hello
	}
	return nil
}

func (m *Packet) GetHelloRequest() bool {
	if m != nil && m.HelloRequest != nil {
		return *m.HelloRequest
	}
	return false
}

func (m *Packet) GetRetains() []*Retains {
	if m != nil {
		return m.Retains
	}
	return nil
}

func (m *Packet) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Packet) GetRequestId() []byte {
	if m != nil {
		return m.RequestId
	}
	return nil
}

func (m *Packet) GetReplyIds() [][]byte {
	if m != nil {
		return m.ReplyIds
	}
	return nil
}

func (m *Packet) GetBebug() []string {
	if m != nil {
		return m.Bebug
	}
	return nil
}

type StaticLink struct {
	Id               *StaticId `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name             *string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Sources          []string  `protobuf:"bytes,3,rep,name=sources" json:"sources,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *StaticLink) Reset()         { *m = StaticLink{} }
func (m *StaticLink) String() string { return proto.CompactTextString(m) }
func (*StaticLink) ProtoMessage()    {}

func (m *StaticLink) GetId() *StaticId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *StaticLink) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *StaticLink) GetSources() []string {
	if m != nil {
		return m.Sources
	}
	return nil
}

func init() {
}
